### ISSUE TITLE
Data: Travel Grant Program information and application form

### ISSUE THREAD

**Issue by alpha-beta-soup** [foss4g-oceania/hoverboard#1]
Date: Planning to open call 31 May or earlier if possible
Content Owner: kimnewzealand

**Comment by alpha-beta-soup** [comment]
Dionne asked me to convert this to an issue to spin out a discussion. I think she still needs @johnwbryant or @dwsilk (https://github.com/orgs/foss4g-oceania/people Owners) to add her so she can add comments and things. Pinging @kimnewzealand as well since I think Dionne wanted some clarification on this.

**Comment by johnwbryant** [comment]
OK just added Dionne to the team, she should get an invite. Let me know if there's anyone else I can add?

**Comment by dnhansen50** [comment]
Are there more information docs aimed at the public about filling in the TGP application to be successful?

**Comment by johnwbryant** [comment]
Good question - we're currently working on wrapping up [this public doc](https://docs.google.com/document/d/1lhA1rQkcI40EQiOKv7oIDc0Dw-9PZET6p-WN0yPNtsc) which will lay out the details of the TGP - we'll make sure public comms are a part of that. Maybe we can touch base in the next week to close any gaps?

**Comment by dnhansen50** [comment]
Sounds good. :)

**Comment by alpha-beta-soup** [comment]
TGP doc is Markdown-ised and lives here: https://github.com/foss4g-oceania/hoverboard/blob/master/data/travel.md, which populates this page: https://foss4g-oceania-c8ffd.firebaseapp.com/tgp (currently broken until I sort out a bug, hopefully tonight).

**Comment by dwsilk** [comment]
Done: https://2019.foss4g-oceania.org/tgp
