### ISSUE TITLE
Should related conferences include others

### ISSUE THREAD

**Issue by kimnewzealand** [foss4g-oceania/hoverboard#12]
On the About page there is a list of Related Conferences, should this include the Bucharest one too? https://2019.foss4g.org/

> Related Conferences
FOSS4G SotM Oceania 2018
FOSS4G-NA 2019

**Comment by johnwbryant** [comment]
Agree, we should prob remove NA and add SotM as well
https://stateofthemap.org/

**Comment by johnwbryant** [comment]
Ahh I see SotM is under 'About' - I suggest moving that under Related Conferences, and perhaps adding [OSM Foundation](https://osmfoundation.org) under About

**Comment by dwsilk** [comment]
Removed FOSS4G NA 2019, added FOSS4G 2019 and State of the Map 2019 under Related Conferences
Replaced SotM with OSM Foundation under About
