### ISSUE TITLE
Venue location map only shows National Library, not VUW Pipitea

### ISSUE THREAD

**Issue by alpha-beta-soup** [foss4g-oceania/hoverboard#23]
... and VUW Pipitea is probably harder to Google and/or find.

**Comment by dwsilk** [comment]
The map marker also appears to be broken for me today?

**Comment by alpha-beta-soup** [comment]
Still looks OK for me. Which browser?

**Comment by dwsilk** [comment]
Chrome on Ubuntu. Working in Firefox. Hmm.
