### ISSUE TITLE
Schedule page has blank top menu options

### ISSUE THREAD

**Issue by kimnewzealand** [foss4g-oceania/hoverboard#7]
https://2019.foss4g-oceania.org/schedule/

**Comment by alpha-beta-soup** [comment]
I'm not sure what you mean.

Here's what I see on my (ludicrously large vertical) screen

![Screenshot from 2019-06-02 21-18-38](https://user-images.githubusercontent.com/5925045/58759318-12d68b80-857c-11e9-8670-9a30b4c8ff72.png)

**Comment by dwsilk** [comment]
So, it seems like the header text either gets stuck on grey for every page or stuck on white for every page if I just randomly click on pages. There must be some pattern to this but this page can end up looking like:

![image](https://user-images.githubusercontent.com/8953184/58759730-ed00b500-8582-11e9-9c33-372e20000e5c.png)

**Comment by alpha-beta-soup** [comment]
Ah I see. OK I'll try track down the pattern and find a fix.

**Comment by dwsilk** [comment]
Fixed by https://github.com/foss4g-oceania/hoverboard/commit/d6742c6
