### ISSUE TITLE
TGP menu option missing from website

### ISSUE THREAD

**Issue by kimnewzealand** [foss4g-oceania/hoverboard#8]
It is not obvious how to navigate to the TGP https://2019.foss4g-oceania.org/tgp from the Homepage, should there be a TGP menu button?

**Comment by dwsilk** [comment]
Added one in the footer via #17 for starters

**Comment by alpha-beta-soup** [comment]
Easily done if we need one; but I was wary of adding too much to the menu, since the same could be said for the other "documents", such as the child friendly conference details, which are linked in content.

Perhaps we need some kind of drop-down sub-menu?

**Comment by kimnewzealand** [comment]
under Attend? I think at the bottom is still too hidden

**Comment by alpha-beta-soup** [comment]
I always figured people would be directed to the TGP via direct link in an email newsletter.

**Comment by kimnewzealand** [comment]
@johnwbryant what do you think ?

**Comment by johnwbryant** [comment]
My opinion: people should be able to go to the website and find whatever
they're looking for. That way, we can always say 'just head to our
website', and also leaves the pathway open for serendipitous discovery.

Could we have some kind of submenu item under Attend?

**Comment by alpha-beta-soup** [comment]
So four options in my mind:

- Include the entire document content within [`/attend/`](https://2019.foss4g-oceania.org/attend/). (In addition to the existing [`/tgp/`](https://2019.foss4g-oceania.org/tgp/).)
- [`/attend/`](https://2019.foss4g-oceania.org/attend/) could include a short blurb about the TGP, with a link to [`/tgp/`](https://2019.foss4g-oceania.org/tgp/).
- A sub-menu in the Attend navigation item itself.
- Make TGP its own navigation item (even if temporarily until applications close). This is distinct from making it a sub-menu item under Attend.

A sub-menu is tricky, I don't really want to deviate from the primary fork's navigation structure. The others are easy. I favour the second option.

**Comment by johnwbryant** [comment]
The second option seems OK to me... so we'd essentially use the /attend
page as a content directory of sorts?

**Comment by alpha-beta-soup** [comment]
Yeah, it's a page with information about "attending", so it makes sense to me to place some information and a link to the full TGP there. The TGP itself would still be a separate page, so it's linkable and there's one page with expanded content just about the TGP. But it's not part of the site navigation.

**Comment by dwsilk** [comment]
There is now a footer link + a blurb on `/attend` with a link + a banner on the front page immediately under the main logo with a link. Sufficient?
